// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: platformtest/i18n/v1/entities.proto

// Messages for the tests of the i18n package.

package testpb

import (
	i18npb "github.com/aidarbn/platform-go/kit/i18nx/i18npb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_platformtest_i18n_v1_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_i18n_v1_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_platformtest_i18n_v1_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	Featured      *Product               `protobuf:"bytes,3,opt,name=featured,proto3" json:"featured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_platformtest_i18n_v1_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_i18n_v1_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_platformtest_i18n_v1_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Menu) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *Menu) GetFeatured() *Product {
	if x != nil {
		return x.Featured
	}
	return nil
}

type ProductEditor struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Id                int64                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FieldTranslations map[string]*i18npb.LocaleMap `protobuf:"bytes,10,rep,name=field_translations,json=fieldTranslations,proto3" json:"field_translations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Variants          []*ProductEditor             `protobuf:"bytes,11,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProductEditor) Reset() {
	*x = ProductEditor{}
	mi := &file_platformtest_i18n_v1_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductEditor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductEditor) ProtoMessage() {}

func (x *ProductEditor) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_i18n_v1_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductEditor.ProtoReflect.Descriptor instead.
func (*ProductEditor) Descriptor() ([]byte, []int) {
	return file_platformtest_i18n_v1_entities_proto_rawDescGZIP(), []int{2}
}

func (x *ProductEditor) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductEditor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductEditor) GetFieldTranslations() map[string]*i18npb.LocaleMap {
	if x != nil {
		return x.FieldTranslations
	}
	return nil
}

func (x *ProductEditor) GetVariants() []*ProductEditor {
	if x != nil {
		return x.Variants
	}
	return nil
}

var File_platformtest_i18n_v1_entities_proto protoreflect.FileDescriptor

const file_platformtest_i18n_v1_entities_proto_rawDesc = "" +
	"\n" +
	"#platformtest/i18n/v1/entities.proto\x12\x14platformtest.i18n.v1\x1a\x1bplatform/i18n/v1/i18n.proto\"\x86\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16\x8a\xb5\x18\x12\n" +
	"\fproduct.name\x12\x02idR\x04name\x12?\n" +
	"\vdescription\x18\x03 \x01(\tB\x1d\x8a\xb5\x18\x19\n" +
	"\x13product.description\x12\x02idR\vdescription\"\xa4\x01\n" +
	"\x04Menu\x12&\n" +
	"\x05title\x18\x01 \x01(\tB\x10\x8a\xb5\x18\f\n" +
	"\n" +
	"menu.titleR\x05title\x129\n" +
	"\bproducts\x18\x02 \x03(\v2\x1d.platformtest.i18n.v1.ProductR\bproducts\x129\n" +
	"\bfeatured\x18\x03 \x01(\v2\x1d.platformtest.i18n.v1.ProductR\bfeatured\"\xda\x02\n" +
	"\rProductEditor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x04name\x18\x02 \x01(\tB\x16\x8a\xb5\x18\x12\n" +
	"\fproduct.name\x12\x02idR\x04name\x12i\n" +
	"\x12field_translations\x18\n" +
	" \x03(\v2:.platformtest.i18n.v1.ProductEditor.FieldTranslationsEntryR\x11fieldTranslations\x12?\n" +
	"\bvariants\x18\v \x03(\v2#.platformtest.i18n.v1.ProductEditorR\bvariants\x1aa\n" +
	"\x16FieldTranslationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.platform.i18n.v1.LocaleMapR\x05value:\x028\x01BAZ?github.com/aidarbn/platform-go/kit/i18nx/internal/testpb;testpbb\x06proto3"

var (
	file_platformtest_i18n_v1_entities_proto_rawDescOnce sync.Once
	file_platformtest_i18n_v1_entities_proto_rawDescData []byte
)

func file_platformtest_i18n_v1_entities_proto_rawDescGZIP() []byte {
	file_platformtest_i18n_v1_entities_proto_rawDescOnce.Do(func() {
		file_platformtest_i18n_v1_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platformtest_i18n_v1_entities_proto_rawDesc), len(file_platformtest_i18n_v1_entities_proto_rawDesc)))
	})
	return file_platformtest_i18n_v1_entities_proto_rawDescData
}

var file_platformtest_i18n_v1_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platformtest_i18n_v1_entities_proto_goTypes = []any{
	(*Product)(nil),          // 0: platformtest.i18n.v1.Product
	(*Menu)(nil),             // 1: platformtest.i18n.v1.Menu
	(*ProductEditor)(nil),    // 2: platformtest.i18n.v1.ProductEditor
	nil,                      // 3: platformtest.i18n.v1.ProductEditor.FieldTranslationsEntry
	(*i18npb.LocaleMap)(nil), // 4: platform.i18n.v1.LocaleMap
}
var file_platformtest_i18n_v1_entities_proto_depIdxs = []int32{
	0, // 0: platformtest.i18n.v1.Menu.products:type_name -> platformtest.i18n.v1.Product
	0, // 1: platformtest.i18n.v1.Menu.featured:type_name -> platformtest.i18n.v1.Product
	3, // 2: platformtest.i18n.v1.ProductEditor.field_translations:type_name -> platformtest.i18n.v1.ProductEditor.FieldTranslationsEntry
	2, // 3: platformtest.i18n.v1.ProductEditor.variants:type_name -> platformtest.i18n.v1.ProductEditor
	4, // 4: platformtest.i18n.v1.ProductEditor.FieldTranslationsEntry.value:type_name -> platform.i18n.v1.LocaleMap
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_platformtest_i18n_v1_entities_proto_init() }
func file_platformtest_i18n_v1_entities_proto_init() {
	if File_platformtest_i18n_v1_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platformtest_i18n_v1_entities_proto_rawDesc), len(file_platformtest_i18n_v1_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platformtest_i18n_v1_entities_proto_goTypes,
		DependencyIndexes: file_platformtest_i18n_v1_entities_proto_depIdxs,
		MessageInfos:      file_platformtest_i18n_v1_entities_proto_msgTypes,
	}.Build()
	File_platformtest_i18n_v1_entities_proto = out.File
	file_platformtest_i18n_v1_entities_proto_goTypes = nil
	file_platformtest_i18n_v1_entities_proto_depIdxs = nil
}
