package codegen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"go.yaml.in/yaml/v3"
)

// Paths of the API generation, relative to the project root.
const (
	ProtoDir    = "proto"
	APIGenDir   = "internal/api/gen"
	OpenAPIFile = "api/openapi/openapi.yaml"
	bufLock     = "buf.lock"
	bufYAML     = "buf.yaml"
	protoMark   = "// Code generated by protoc-gen-"
)

// Protos returns the proto files of the project.
func Protos(dir string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(filepath.Join(dir, ProtoDir), func(path string, d fs.DirEntry, err error) error {
		if errors.Is(err, fs.ErrNotExist) {
			return fs.SkipAll
		}
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(dir, path)
		// The platform's own proto files are imported, not generated.
		if d.IsDir() && filepath.ToSlash(rel) == "proto/platform" {
			return fs.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(path, ".proto") {
			out = append(out, filepath.ToSlash(rel))
		}
		return nil
	})
	slices.Sort(out)
	return out, err
}

// Buf regenerates the Go code and the OpenAPI description of the proto files. Without
// proto files it only removes what was generated before.
func Buf(ctx context.Context, dir string, out io.Writer) error {
	protos, err := Protos(dir)
	if err != nil {
		return err
	}
	if err := removeGenerated(dir, APIGenDir, protoMark); err != nil {
		return err
	}
	if len(protos) == 0 {
		if err := os.Remove(filepath.Join(dir, OpenAPIFile)); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	if err := ensureBufLock(ctx, dir, out); err != nil {
		return err
	}
	return GoCommand(ctx, dir, out, "tool", "buf", "generate")
}

// BufCheck fails when the generated API code does not match the proto files: for CI. It
// generates into a scratch directory and compares, so the project is not touched.
func BufCheck(ctx context.Context, dir string) error {
	protos, err := Protos(dir)
	if err != nil {
		return err
	}
	current, err := apiOutputs(dir)
	if err != nil {
		return err
	}
	if len(protos) == 0 {
		if len(current) > 0 {
			return fmt.Errorf("%s has code for proto files that no longer exist, run platformgo generate", APIGenDir)
		}
		return nil
	}
	if _, err := os.Stat(filepath.Join(dir, bufLock)); err != nil {
		return fmt.Errorf("%s is missing, run platformgo generate", bufLock)
	}

	scratch, err := os.MkdirTemp("", "platformgo-buf-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(scratch)

	var stderr bytes.Buffer
	if err := GoCommand(ctx, dir, &stderr, "tool", "buf", "generate", "--output", scratch); err != nil {
		return err
	}
	fresh, err := apiOutputs(scratch)
	if err != nil {
		return err
	}

	var stale []string
	for path, content := range fresh {
		if !bytes.Equal(current[path], content) {
			stale = append(stale, path)
		}
	}
	for path := range current {
		if _, ok := fresh[path]; !ok {
			stale = append(stale, path)
		}
	}
	if len(stale) > 0 {
		slices.Sort(stale)
		return fmt.Errorf("generated API code is stale, run platformgo generate: %s", strings.Join(stale, ", "))
	}
	return nil
}

// apiOutputs reads what buf generates under root: the marked Go files and the OpenAPI
// description.
func apiOutputs(root string) (map[string][]byte, error) {
	out := map[string][]byte{}
	err := filepath.WalkDir(filepath.Join(root, APIGenDir), func(path string, d fs.DirEntry, err error) error {
		if errors.Is(err, fs.ErrNotExist) {
			return fs.SkipAll
		}
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") {
			return err
		}
		marked, err := hasMark(path, protoMark)
		if err != nil || !marked {
			return err
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, path)
		out[filepath.ToSlash(rel)] = content
		return nil
	})
	if err != nil {
		return nil, err
	}
	if content, err := os.ReadFile(filepath.Join(root, OpenAPIFile)); err == nil {
		out[OpenAPIFile] = content
	} else if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	return out, nil
}

// ensureBufLock resolves the proto dependencies; buf.lock then pins them and is committed
// with the project. It resolves again when buf.lock pins a different set than buf.yaml
// declares: a platform upgrade that adds a dependency rewrites buf.yaml, and a lock left
// as it was fails generation with an import buf cannot find.
func ensureBufLock(ctx context.Context, dir string, out io.Writer) error {
	stale, err := bufLockStale(dir)
	if err != nil || !stale {
		return err
	}
	return GoCommand(ctx, dir, out, "tool", "buf", "dep", "update")
}

// bufLockStale reports whether buf.lock is missing or pins other dependencies than
// buf.yaml declares. Versions are not compared: pinning them is what the lock is for.
func bufLockStale(dir string) (bool, error) {
	lock, err := os.ReadFile(filepath.Join(dir, bufLock))
	if errors.Is(err, os.ErrNotExist) {
		return true, nil
	}
	if err != nil {
		return false, err
	}
	config, err := os.ReadFile(filepath.Join(dir, bufYAML))
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	var declared struct {
		Deps []string `yaml:"deps"`
	}
	if err := yaml.Unmarshal(config, &declared); err != nil {
		return false, fmt.Errorf("%s: %w", bufYAML, err)
	}
	var pinned struct {
		Deps []struct {
			Name string `yaml:"name"`
		} `yaml:"deps"`
	}
	if err := yaml.Unmarshal(lock, &pinned); err != nil {
		return false, fmt.Errorf("%s: %w", bufLock, err)
	}
	names := make([]string, 0, len(pinned.Deps))
	for _, d := range pinned.Deps {
		names = append(names, d.Name)
	}
	slices.Sort(declared.Deps)
	slices.Sort(names)
	return !slices.Equal(declared.Deps, names), nil
}
