package codegen_test

import (
	"context"
	"io"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/aidarbn/platform-go/internal/codegen"
)

const pbFile = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage ordersv1\n"

// fakeBuf behaves like buf: generate writes the Go code and the OpenAPI description under
// the --output directory, dep update writes buf.lock.
func fakeBuf(t *testing.T, pb string) *[][]string {
	t.Helper()
	var calls [][]string
	orig := codegen.GoCommand
	t.Cleanup(func() { codegen.GoCommand = orig })
	codegen.GoCommand = func(_ context.Context, dir string, _ io.Writer, args ...string) error {
		calls = append(calls, args)
		switch {
		case slices.Contains(args, "update"):
			write(t, dir, "buf.lock", "version: v2\n")
		case slices.Contains(args, "generate"):
			base := dir
			if i := slices.Index(args, "--output"); i >= 0 {
				base = args[i+1]
			}
			write(t, base, "internal/api/gen/orders/v1/orders.pb.go", pb)
			write(t, base, "api/openapi/openapi.yaml", "openapi: 3.1.0\n")
		}
		return nil
	}
	return &calls
}

func TestBufGenerates(t *testing.T) {
	dir := t.TempDir()
	calls := fakeBuf(t, pbFile)
	write(t, dir, "proto/orders/v1/orders.proto", `syntax = "proto3";`)
	write(t, dir, "internal/api/gen/removed/v1/removed.pb.go", pbFile)

	if err := codegen.Buf(context.Background(), dir, io.Discard); err != nil {
		t.Fatalf("Buf: %v", err)
	}
	// The dependencies are resolved once, then the code is generated.
	if len(*calls) != 2 || !slices.Contains((*calls)[0], "update") || !slices.Contains((*calls)[1], "generate") {
		t.Errorf("calls = %v", *calls)
	}
	if exists(dir, "internal/api/gen/removed/v1/removed.pb.go") || exists(dir, "internal/api/gen/removed") {
		t.Error("code of a removed proto file stayed")
	}
	if !exists(dir, "internal/api/gen/orders/v1/orders.pb.go") || !exists(dir, "api/openapi/openapi.yaml") {
		t.Error("the fresh code is missing")
	}

	// buf.lock exists now: no second dep update.
	*calls = nil
	if err := codegen.Buf(context.Background(), dir, io.Discard); err != nil {
		t.Fatalf("Buf: %v", err)
	}
	if len(*calls) != 1 {
		t.Errorf("calls = %v", *calls)
	}
}

func TestBufWithoutProtosCleansUp(t *testing.T) {
	dir := t.TempDir()
	calls := fakeBuf(t, pbFile)
	write(t, dir, "internal/api/gen/orders/v1/orders.pb.go", pbFile)
	write(t, dir, "api/openapi/openapi.yaml", "openapi: 3.1.0\n")

	if err := codegen.Buf(context.Background(), dir, io.Discard); err != nil {
		t.Fatalf("Buf: %v", err)
	}
	if len(*calls) != 0 || exists(dir, "internal/api/gen") || exists(dir, "api/openapi/openapi.yaml") {
		t.Errorf("calls = %v, leftovers stayed", *calls)
	}
}

func TestBufCheck(t *testing.T) {
	ctx := context.Background()

	t.Run("fresh", func(t *testing.T) {
		dir := t.TempDir()
		calls := fakeBuf(t, pbFile)
		write(t, dir, "proto/orders/v1/orders.proto", "")
		write(t, dir, "buf.lock", "version: v2\n")
		write(t, dir, "internal/api/gen/orders/v1/orders.pb.go", pbFile)
		write(t, dir, "api/openapi/openapi.yaml", "openapi: 3.1.0\n")

		if err := codegen.BufCheck(ctx, dir); err != nil {
			t.Fatalf("BufCheck: %v", err)
		}
		// The check generates elsewhere and never touches the project.
		if !slices.Contains((*calls)[0], "--output") {
			t.Errorf("calls = %v", *calls)
		}
	})

	t.Run("stale", func(t *testing.T) {
		dir := t.TempDir()
		fakeBuf(t, pbFile)
		write(t, dir, "proto/orders/v1/orders.proto", "")
		write(t, dir, "buf.lock", "version: v2\n")
		write(t, dir, "internal/api/gen/orders/v1/orders.pb.go", pbFile+"// old\n")
		write(t, dir, "internal/api/gen/gone/v1/gone.pb.go", pbFile)

		err := codegen.BufCheck(ctx, dir)
		if err == nil {
			t.Fatal("stale code passed the check")
		}
		for _, want := range []string{"orders.pb.go", "gone.pb.go", "api/openapi/openapi.yaml"} {
			if !strings.Contains(err.Error(), want) {
				t.Errorf("the error does not name %s: %v", want, err)
			}
		}
		content, _ := readFile(dir, "internal/api/gen/orders/v1/orders.pb.go")
		if !strings.HasSuffix(content, "// old\n") {
			t.Error("the check rewrote the project")
		}
	})

	t.Run("no lock", func(t *testing.T) {
		dir := t.TempDir()
		fakeBuf(t, pbFile)
		write(t, dir, "proto/orders/v1/orders.proto", "")
		if err := codegen.BufCheck(ctx, dir); err == nil || !strings.Contains(err.Error(), "buf.lock") {
			t.Fatalf("err = %v", err)
		}
	})

	t.Run("code without protos", func(t *testing.T) {
		dir := t.TempDir()
		fakeBuf(t, pbFile)
		write(t, dir, "internal/api/gen/orders/v1/orders.pb.go", pbFile)
		if err := codegen.BufCheck(ctx, dir); err == nil {
			t.Fatal("code of removed protos passed the check")
		}
	})
}

func TestProtos(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "proto/b/v1/b.proto", "")
	write(t, dir, "proto/a/v1/a.proto", "")
	write(t, dir, "proto/README.md", "")

	got, err := codegen.Protos(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(got, []string{"proto/a/v1/a.proto", "proto/b/v1/b.proto"}) {
		t.Errorf("protos = %v", got)
	}
	if none, err := codegen.Protos(t.TempDir()); err != nil || len(none) != 0 {
		t.Errorf("no proto dir: %v, %v", none, err)
	}
}

func readFile(dir, path string) (string, error) {
	raw, err := readRaw(filepath.Join(dir, path))
	return string(raw), err
}

// The platform's proto files are imported by the project, not generated from it.
func TestProtosSkipPlatformFiles(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "proto/platform/i18n/v1/i18n.proto", "")
	got, err := codegen.Protos(dir)
	if err != nil || len(got) != 0 {
		t.Fatalf("protos = %v, %v", got, err)
	}
	write(t, dir, "proto/shop/v1/orders.proto", "")
	if got, _ := codegen.Protos(dir); len(got) != 1 || got[0] != "proto/shop/v1/orders.proto" {
		t.Errorf("protos = %v", got)
	}
}
