// Package codegen runs the external generators of the postgres module: sqlc for static
// queries and jet for dynamic ones.
//
// Both run through go tool, at the versions the project pins in go.mod, so every
// developer and CI produce the same code.
package codegen

import (
	"bufio"
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"
)

// Paths of the query generation, relative to the project root.
const (
	QueriesDir    = "db/queries"
	MigrationsDir = "db/migrations"
	SqlcConfig    = "db/sqlc.yaml"
	SqlcOut       = "internal/db/sqlcgen"
	JetOut        = "internal/db/jetgen"
)

const (
	sqlcMark = "// Code generated by sqlc"
	jetMark  = "// Code generated by go-jet"
)

// GoCommand runs the go command. Tests replace it.
var GoCommand = func(ctx context.Context, dir string, out io.Writer, args ...string) error {
	cmd := exec.CommandContext(ctx, "go", args...)
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stdout = out
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if strings.Contains(msg, "missing go.sum entry") || strings.Contains(msg, "no required module provides") {
			msg += "\nrun platformgo apply to add the generators to go.mod and go.sum"
		}
		return fmt.Errorf("go %s: %w\n%s", strings.Join(args, " "), err, msg)
	}
	return nil
}

// Queries returns the query files of the project.
func Queries(dir string) ([]string, error) {
	matches, err := filepath.Glob(filepath.Join(dir, QueriesDir, "*.sql"))
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(matches))
	for _, m := range matches {
		out = append(out, filepath.Base(m))
	}
	slices.Sort(out)
	return out, nil
}

// Sqlc regenerates the static queries. Without query files it only removes what sqlc
// generated before, so deleting the last query leaves nothing behind.
func Sqlc(ctx context.Context, dir string, out io.Writer) error {
	queries, err := Queries(dir)
	if err != nil {
		return err
	}
	// A broken query must not cost the code that compiles: sqlc checks the queries
	// before anything is removed.
	if len(queries) > 0 {
		if err := GoCommand(ctx, dir, out, "tool", "sqlc", "compile", "-f", SqlcConfig); err != nil {
			return err
		}
	}
	// sqlc does not remove the output of a deleted query file, so the old output goes
	// first.
	if err := removeGenerated(dir, SqlcOut, sqlcMark); err != nil {
		return err
	}
	if len(queries) == 0 {
		return nil
	}
	return GoCommand(ctx, dir, out, "tool", "sqlc", "generate", "-f", SqlcConfig)
}

// SqlcCheck fails when the sqlc output does not match the queries: for CI.
func SqlcCheck(ctx context.Context, dir string) error {
	queries, err := Queries(dir)
	if err != nil {
		return err
	}

	generated, err := generatedFiles(filepath.Join(dir, SqlcOut), sqlcMark)
	if err != nil {
		return err
	}
	// Output of a query file that no longer exists: sqlc diff does not see it.
	for _, name := range generated {
		if query, ok := strings.CutSuffix(name, ".sql.go"); ok && !slices.Contains(queries, query+".sql") {
			return fmt.Errorf("%s/%s is left from a removed query, run platformgo generate", SqlcOut, name)
		}
	}
	if len(queries) == 0 {
		if len(generated) > 0 {
			return fmt.Errorf("%s has code for queries that no longer exist, run platformgo generate", SqlcOut)
		}
		return nil
	}

	var diff bytes.Buffer
	if err := GoCommand(ctx, dir, &diff, "tool", "sqlc", "diff", "-f", SqlcConfig); err != nil {
		return fmt.Errorf("sqlc output is stale, run platformgo generate\n%s%w", diff.String(), err)
	}
	return nil
}

// Jet regenerates the dynamic query builder from the database at dsn. The schema must
// already be migrated; the tables of goose, River and platform modules are left out.
//
// jet writes into <path>/<database>/<schema>. The database name differs between
// developers, and it would end up in import paths, so the output is generated into a
// scratch directory and its packages are moved straight under internal/db/jetgen.
func Jet(ctx context.Context, dir, dsn string, out io.Writer) error {
	scratch, err := os.MkdirTemp(dir, ".jetgen-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(scratch)

	rel, err := filepath.Rel(dir, scratch)
	if err != nil {
		return err
	}
	if err := GoCommand(ctx, dir, out, "tool", "jet",
		"-dsn="+dsn,
		"-schema=public",
		"-path="+filepath.ToSlash(rel),
		"-ignore-tables=goose_db_version,platform_*,river_*",
	); err != nil {
		return err
	}

	schemaDir, err := findSchemaDir(scratch)
	if err != nil {
		return err
	}
	if err := removeGenerated(dir, JetOut, jetMark); err != nil {
		return err
	}
	target := filepath.Join(dir, JetOut)
	if err := os.MkdirAll(target, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(schemaDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		dst := filepath.Join(target, e.Name())
		if _, err := os.Stat(dst); err == nil {
			return fmt.Errorf("%s/%s has files written by hand; move them out of the generated folder", JetOut, e.Name())
		}
		if err := os.Rename(filepath.Join(schemaDir, e.Name()), dst); err != nil {
			return err
		}
	}
	return nil
}

// findSchemaDir returns <scratch>/<database>/<schema>, the only place jet writes to.
func findSchemaDir(scratch string) (string, error) {
	dbs, err := os.ReadDir(scratch)
	if err != nil {
		return "", err
	}
	if len(dbs) != 1 || !dbs[0].IsDir() {
		return "", fmt.Errorf("jet wrote an unexpected layout into %s", scratch)
	}
	schemas, err := os.ReadDir(filepath.Join(scratch, dbs[0].Name()))
	if err != nil {
		return "", err
	}
	if len(schemas) != 1 || !schemas[0].IsDir() {
		return "", fmt.Errorf("jet wrote an unexpected layout into %s", scratch)
	}
	return filepath.Join(scratch, dbs[0].Name(), schemas[0].Name()), nil
}

// removeGenerated deletes the files carrying the generator mark under rel and the
// folders that become empty, up to the project root. A file without the mark was
// written by hand and stays.
func removeGenerated(project, rel, mark string) error {
	root := filepath.Join(project, rel)
	var dirs []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if errors.Is(err, os.ErrNotExist) {
			return filepath.SkipDir
		}
		if err != nil {
			return err
		}
		if d.IsDir() {
			dirs = append(dirs, path)
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}
		generated, err := hasMark(path, mark)
		if err != nil {
			return err
		}
		if generated {
			return os.Remove(path)
		}
		return nil
	})
	if err != nil {
		return err
	}
	// Deepest first, so a parent becomes empty after its children are gone.
	slices.Reverse(dirs)
	for _, d := range dirs {
		_ = os.Remove(d) // fails when not empty, which is fine
	}
	for parent := filepath.Dir(root); parent != filepath.Clean(project) && strings.HasPrefix(parent, filepath.Clean(project)); parent = filepath.Dir(parent) {
		if os.Remove(parent) != nil {
			break
		}
	}
	return nil
}

func generatedFiles(root, mark string) ([]string, error) {
	entries, err := os.ReadDir(root)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		generated, err := hasMark(filepath.Join(root, e.Name()), mark)
		if err != nil {
			return nil, err
		}
		if generated {
			out = append(out, e.Name())
		}
	}
	return out, nil
}

func hasMark(path, mark string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()

	// The mark sits in the header, before the package clause.
	scanner := bufio.NewScanner(f)
	for i := 0; i < 5 && scanner.Scan(); i++ {
		if strings.HasPrefix(scanner.Text(), mark) {
			return true, nil
		}
	}
	return false, scanner.Err()
}

// DSN finds the database address for generation: the flag, then DATABASE_URL, then the
// .env and .env.example of the project — the same order make run uses.
func DSN(dir, flag string) (string, error) {
	if flag != "" {
		return flag, nil
	}
	if v := strings.TrimSpace(os.Getenv("DATABASE_URL")); v != "" {
		return v, nil
	}
	for _, name := range []string{".env", ".env.example"} {
		v, err := envValue(filepath.Join(dir, name), "DATABASE_URL")
		if err != nil {
			return "", err
		}
		if v != "" {
			return v, nil
		}
	}
	return "", errors.New("no database address: pass --dsn, set DATABASE_URL or add it to .env")
}

func envValue(path, key string) (string, error) {
	f, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		line = strings.TrimPrefix(line, "export ")
		name, value, ok := strings.Cut(line, "=")
		if !ok || strings.HasPrefix(line, "#") || strings.TrimSpace(name) != key {
			continue
		}
		return strings.Trim(strings.TrimSpace(value), `"'`), nil
	}
	return "", scanner.Err()
}
