package codegen_test

import (
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/aidarbn/platform-go/internal/codegen"
)

type call struct {
	dir  string
	args []string
}

// fakeGo records go commands instead of running them.
func fakeGo(t *testing.T, fail error) *[]call {
	t.Helper()
	var calls []call
	orig := codegen.GoCommand
	codegen.GoCommand = func(_ context.Context, dir string, _ io.Writer, args ...string) error {
		calls = append(calls, call{dir: dir, args: args})
		return fail
	}
	t.Cleanup(func() { codegen.GoCommand = orig })
	return &calls
}

func write(t *testing.T, dir, path, content string) {
	t.Helper()
	full := filepath.Join(dir, path)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func exists(dir, path string) bool {
	_, err := os.Stat(filepath.Join(dir, path))
	return err == nil
}

const sqlcFile = "// Code generated by sqlc. DO NOT EDIT.\n// versions:\n\npackage sqlcgen\n"

func TestSqlcRunsWithQueries(t *testing.T) {
	dir := t.TempDir()
	calls := fakeGo(t, nil)
	write(t, dir, "db/queries/orders.sql", "-- name: GetOrder :one\nSELECT 1;\n")
	write(t, dir, "internal/db/sqlcgen/removed.sql.go", sqlcFile)
	write(t, dir, "internal/db/sqlcgen/helpers.go", "package sqlcgen\n\n// Written by hand.\n")

	if err := codegen.Sqlc(context.Background(), dir, io.Discard); err != nil {
		t.Fatalf("Sqlc: %v", err)
	}
	if len(*calls) != 1 || !slices.Equal((*calls)[0].args, []string{"tool", "sqlc", "generate", "-f", "db/sqlc.yaml"}) {
		t.Errorf("calls = %+v", *calls)
	}
	// Old output goes before generating: sqlc does not remove it.
	if exists(dir, "internal/db/sqlcgen/removed.sql.go") {
		t.Error("old sqlc output stayed")
	}
	if !exists(dir, "internal/db/sqlcgen/helpers.go") {
		t.Error("a file written by hand was deleted")
	}
}

func TestSqlcWithoutQueriesCleansUp(t *testing.T) {
	dir := t.TempDir()
	calls := fakeGo(t, nil)
	write(t, dir, "internal/db/sqlcgen/db.go", sqlcFile)

	if err := codegen.Sqlc(context.Background(), dir, io.Discard); err != nil {
		t.Fatalf("Sqlc: %v", err)
	}
	if len(*calls) != 0 {
		t.Errorf("sqlc ran without queries: %+v", *calls)
	}
	if exists(dir, "internal/db/sqlcgen") || exists(dir, "internal/db") {
		t.Error("the output of the last query was not removed with its folders")
	}
}

func TestSqlcCheck(t *testing.T) {
	ctx := context.Background()

	t.Run("fresh", func(t *testing.T) {
		dir := t.TempDir()
		calls := fakeGo(t, nil)
		write(t, dir, "db/queries/orders.sql", "")
		write(t, dir, "internal/db/sqlcgen/orders.sql.go", sqlcFile)
		if err := codegen.SqlcCheck(ctx, dir); err != nil {
			t.Fatalf("SqlcCheck: %v", err)
		}
		if len(*calls) != 1 || !slices.Contains((*calls)[0].args, "diff") {
			t.Errorf("calls = %+v", *calls)
		}
	})

	t.Run("stale diff", func(t *testing.T) {
		dir := t.TempDir()
		fakeGo(t, errors.New("exit status 1"))
		write(t, dir, "db/queries/orders.sql", "")
		if err := codegen.SqlcCheck(ctx, dir); err == nil || !strings.Contains(err.Error(), "sqlc output is stale") {
			t.Fatalf("err = %v", err)
		}
	})

	// sqlc diff does not know about the output of a query file that was deleted.
	t.Run("leftover of a removed query", func(t *testing.T) {
		dir := t.TempDir()
		fakeGo(t, nil)
		write(t, dir, "db/queries/orders.sql", "")
		write(t, dir, "internal/db/sqlcgen/customers.sql.go", sqlcFile)
		if err := codegen.SqlcCheck(ctx, dir); err == nil || !strings.Contains(err.Error(), "customers.sql.go") {
			t.Fatalf("err = %v", err)
		}
	})

	t.Run("output without queries", func(t *testing.T) {
		dir := t.TempDir()
		calls := fakeGo(t, nil)
		write(t, dir, "internal/db/sqlcgen/db.go", sqlcFile)
		if err := codegen.SqlcCheck(ctx, dir); err == nil {
			t.Fatal("output of removed queries passed the check")
		}
		if len(*calls) != 0 {
			t.Errorf("sqlc ran: %+v", *calls)
		}
	})

	t.Run("nothing at all", func(t *testing.T) {
		fakeGo(t, nil)
		if err := codegen.SqlcCheck(ctx, t.TempDir()); err != nil {
			t.Fatalf("SqlcCheck: %v", err)
		}
	})
}

const jetFile = "//\n// Code generated by go-jet DO NOT EDIT.\n\npackage table\n"

func TestJet(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "internal/db/jetgen/table/removed.go", jetFile)

	var args []string
	orig := codegen.GoCommand
	t.Cleanup(func() { codegen.GoCommand = orig })
	// The fake behaves like jet: it writes into <path>/<database>/<schema>.
	codegen.GoCommand = func(_ context.Context, dir string, _ io.Writer, a ...string) error {
		args = a
		var path string
		for _, arg := range a {
			if v, ok := strings.CutPrefix(arg, "-path="); ok {
				path = v
			}
		}
		write(t, dir, filepath.Join(path, "devdb", "public", "table", "orders.go"), jetFile)
		write(t, dir, filepath.Join(path, "devdb", "public", "model", "orders.go"), strings.Replace(jetFile, "table", "model", 1))
		return nil
	}

	if err := codegen.Jet(context.Background(), dir, "postgres://app:app@localhost/devdb", io.Discard); err != nil {
		t.Fatalf("Jet: %v", err)
	}

	// The database name is not part of the import path.
	for _, path := range []string{"internal/db/jetgen/table/orders.go", "internal/db/jetgen/model/orders.go"} {
		if !exists(dir, path) {
			t.Errorf("%s is missing", path)
		}
	}
	if exists(dir, "internal/db/jetgen/devdb") || exists(dir, "internal/db/jetgen/table/removed.go") {
		t.Error("the layout of jet or the old builder stayed")
	}
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".jetgen-") {
			t.Errorf("the scratch directory stayed: %s", e.Name())
		}
	}
	joined := strings.Join(args, " ")
	for _, want := range []string{"tool jet", "-dsn=postgres://app:app@localhost/devdb", "-schema=public", "-ignore-tables=goose_db_version,platform_*,river_*"} {
		if !strings.Contains(joined, want) {
			t.Errorf("jet args lack %q: %s", want, joined)
		}
	}
}

func TestJetFailureKeepsOldBuilder(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "internal/db/jetgen/table/orders.go", jetFile)
	fakeGo(t, errors.New("connection refused"))

	if err := codegen.Jet(context.Background(), dir, "postgres://nowhere", io.Discard); err == nil {
		t.Fatal("a failed generation was reported as success")
	}
	if !exists(dir, "internal/db/jetgen/table/orders.go") {
		t.Error("a failed generation deleted the builder the project compiles against")
	}
}

func TestDSN(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("DATABASE_URL", "")

	if _, err := codegen.DSN(dir, ""); err == nil {
		t.Error("no address anywhere was accepted")
	}

	write(t, dir, ".env.example", "# example\nDATABASE_URL=postgres://example\n")
	if got, _ := codegen.DSN(dir, ""); got != "postgres://example" {
		t.Errorf(".env.example: %q", got)
	}

	write(t, dir, ".env", "export DATABASE_URL=\"postgres://dotenv\"\n")
	if got, _ := codegen.DSN(dir, ""); got != "postgres://dotenv" {
		t.Errorf(".env: %q", got)
	}

	t.Setenv("DATABASE_URL", "postgres://env")
	if got, _ := codegen.DSN(dir, ""); got != "postgres://env" {
		t.Errorf("env: %q", got)
	}

	if got, _ := codegen.DSN(dir, "postgres://flag"); got != "postgres://flag" {
		t.Errorf("flag: %q", got)
	}
}

func readRaw(path string) ([]byte, error) { return os.ReadFile(path) }
