package codegen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const templMark = "// Code generated by templ - DO NOT EDIT."

// skipDir tells the walks over project files which directories are not the project's.
func skipDir(name string) bool {
	return name == "vendor" || name == "node_modules" || name == "testdata" || strings.HasPrefix(name, ".")
}

// Templates returns the templ files of the project.
func Templates(dir string) ([]string, error) {
	var out []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != dir && skipDir(d.Name()) {
				return fs.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(path, ".templ") {
			rel, _ := filepath.Rel(dir, path)
			out = append(out, filepath.ToSlash(rel))
		}
		return nil
	})
	slices.Sort(out)
	return out, err
}

// templOutput is the Go file templ writes next to a template.
func templOutput(template string) string {
	return strings.TrimSuffix(template, ".templ") + "_templ.go"
}

// orphanTemplOutputs are generated files whose template is gone.
func orphanTemplOutputs(dir string, templates []string) ([]string, error) {
	have := make(map[string]bool, len(templates))
	for _, t := range templates {
		have[templOutput(t)] = true
	}
	var orphans []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != dir && skipDir(d.Name()) {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, "_templ.go") {
			return nil
		}
		rel, _ := filepath.Rel(dir, path)
		rel = filepath.ToSlash(rel)
		if have[rel] {
			return nil
		}
		marked, err := hasMark(path, templMark)
		if err == nil && marked {
			orphans = append(orphans, rel)
		}
		return err
	})
	return orphans, err
}

// Templ regenerates the Go code of the templ files and removes the code of deleted ones.
func Templ(ctx context.Context, dir string, out io.Writer) error {
	templates, err := Templates(dir)
	if err != nil {
		return err
	}
	orphans, err := orphanTemplOutputs(dir, templates)
	if err != nil {
		return err
	}
	for _, o := range orphans {
		if err := os.Remove(filepath.Join(dir, o)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		fmt.Fprintln(out, "deleted", o)
	}
	if len(templates) == 0 {
		return nil
	}
	return GoCommand(ctx, dir, io.Discard, "tool", "templ", "generate", "-path", ".")
}

// TemplCheck fails when the Go code of a template is stale or belongs to a deleted one. It
// renders each template to stdout, so the project is not touched.
func TemplCheck(ctx context.Context, dir string) error {
	templates, err := Templates(dir)
	if err != nil {
		return err
	}
	stale, err := orphanTemplOutputs(dir, templates)
	if err != nil {
		return err
	}
	for _, t := range templates {
		var fresh bytes.Buffer
		if err := GoCommand(ctx, dir, &fresh, "tool", "templ", "generate", "-f", t, "-stdout"); err != nil {
			return err
		}
		current, err := os.ReadFile(filepath.Join(dir, templOutput(t)))
		if err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
		if !bytes.Equal(bytes.TrimSpace(current), bytes.TrimSpace(fresh.Bytes())) {
			stale = append(stale, templOutput(t))
		}
	}
	if len(stale) > 0 {
		slices.Sort(stale)
		return fmt.Errorf("generated template code is stale, run platformgo generate: %s", strings.Join(stale, ", "))
	}
	return nil
}
