package codegen_test

import (
	"context"
	"io"
	"slices"
	"strings"
	"testing"

	"github.com/aidarbn/platform-go/internal/codegen"
)

const templGo = "// Code generated by templ - DO NOT EDIT.\n\npackage views\n"

// fakeTempl stands in for go tool templ: generate writes next to the templates under -path.
func fakeTempl(t *testing.T, code string) *[][]string {
	t.Helper()
	var calls [][]string
	orig := codegen.GoCommand
	t.Cleanup(func() { codegen.GoCommand = orig })
	codegen.GoCommand = func(_ context.Context, dir string, _ io.Writer, args ...string) error {
		calls = append(calls, args)
		root := dir
		if i := slices.Index(args, "-path"); i >= 0 && args[i+1] != "." {
			root = args[i+1]
		}
		templates, _ := codegen.Templates(root)
		for _, tpl := range templates {
			write(t, root, strings.TrimSuffix(tpl, ".templ")+"_templ.go", code)
		}
		return nil
	}
	return &calls
}

func TestTemplGeneratesAndCleansUp(t *testing.T) {
	dir := t.TempDir()
	calls := fakeTempl(t, templGo)
	write(t, dir, "internal/web/views/page.templ", "package views")
	write(t, dir, "internal/web/views/gone_templ.go", templGo)
	write(t, dir, "internal/web/views/hand_templ.go", "package views // written by hand")
	write(t, dir, "node_modules/x/y.templ", "ignored")

	if err := codegen.Templ(context.Background(), dir, io.Discard); err != nil {
		t.Fatal(err)
	}
	if !exists(dir, "internal/web/views/page_templ.go") || exists(dir, "internal/web/views/gone_templ.go") || !exists(dir, "internal/web/views/hand_templ.go") {
		t.Error("generation or cleanup went wrong")
	}
	if len(*calls) != 1 {
		t.Errorf("calls = %v", *calls)
	}
	if err := codegen.TemplCheck(context.Background(), dir); err != nil {
		t.Errorf("fresh code is reported stale: %v", err)
	}
}

func TestTemplCheckFindsStaleCode(t *testing.T) {
	dir := t.TempDir()
	fakeTempl(t, templGo+"// changed\n")
	write(t, dir, "views/page.templ", "package views")
	write(t, dir, "views/page_templ.go", templGo)
	write(t, dir, "views/orphan_templ.go", templGo)

	err := codegen.TemplCheck(context.Background(), dir)
	if err == nil || !strings.Contains(err.Error(), "views/page_templ.go") || !strings.Contains(err.Error(), "views/orphan_templ.go") {
		t.Errorf("err = %v", err)
	}
}
