package lint_test

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/aidarbn/platform-go/internal/lint"
)

func write(t *testing.T, dir, path, content string) {
	t.Helper()
	full := filepath.Join(dir, path)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func TestFormat(t *testing.T) {
	dir := t.TempDir()
	write(t, dir, "ok.go", "package x\n\nfunc A() {}\n")
	if err := lint.Format(dir); err != nil {
		t.Fatalf("Format: %v", err)
	}

	write(t, dir, "internal/bad.go", "package x\nfunc  B( ) {}\n")
	write(t, dir, ".git/ignored.go", "package x\nfunc  C( ) {}\n")
	err := lint.Format(dir)
	if err == nil || !strings.Contains(err.Error(), "internal/bad.go") || strings.Contains(err.Error(), "ignored.go") {
		t.Fatalf("err = %v", err)
	}
}

func TestFiles(t *testing.T) {
	dir := t.TempDir()
	long := "package x\n" + strings.Repeat("// line\n", 20)
	write(t, dir, "short.go", "package x\n")
	write(t, dir, "internal/db/sqlcgen/queries.sql.go", "// Code generated by sqlc. DO NOT EDIT.\n"+long)
	write(t, dir, "internal/api/gen/x.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n"+long)

	if err := lint.Files(dir, 10); err != nil {
		t.Fatalf("generated files must be exempt: %v", err)
	}

	write(t, dir, "internal/orders/service.go", long)
	err := lint.Files(dir, 10)
	if err == nil || !strings.Contains(err.Error(), "internal/orders/service.go has 21 lines (max 10)") {
		t.Fatalf("err = %v", err)
	}
	// A comment mentioning code generation below the package clause is not a header.
	write(t, dir, "internal/orders/service.go", "package x\n// Code generated by hand. DO NOT EDIT.\n"+strings.Repeat("//\n", 20))
	if err := lint.Files(dir, 10); err == nil {
		t.Error("a hand written file escaped the limit")
	}
}

type call struct {
	env  []string
	args []string
}

func TestChecksAndRun(t *testing.T) {
	var calls []call
	run := func(_ context.Context, _ string, _ io.Writer, env []string, name string, args ...string) error {
		calls = append(calls, call{env: env, args: append([]string{name}, args...)})
		if strings.Contains(strings.Join(args, " "), "golangci-lint") {
			return errors.New("errcheck: error return value is not checked")
		}
		return nil
	}
	verified := false
	verify := func(context.Context, string) error { verified = true; return nil }

	dir := t.TempDir()
	write(t, dir, "main.go", "package main\n\nfunc main() {}\n")

	checks := lint.Checks(lint.Options{Modules: []string{"api", "postgres"}, ProtoAgainst: "dev", Skip: []string{"security"}}, run, verify)
	var names []string
	for _, c := range checks {
		names = append(names, c.Name)
	}
	if !slices.Equal(names, []string{"format", "tidy", "build", "generate", "files", "go", "proto"}) {
		t.Fatalf("checks = %v", names)
	}

	var out bytes.Buffer
	err := lint.Run(context.Background(), dir, checks, &out)
	if err == nil || !strings.Contains(err.Error(), "lint failed: go") {
		t.Fatalf("err = %v", err)
	}
	// Every check runs even after one failed, so a run shows everything to fix.
	for _, want := range []string{"ok   format", "ok   generate", "FAIL go", "errcheck", "ok   proto"} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("output lacks %q:\n%s", want, out.String())
		}
	}
	if !verified {
		t.Error("the generation check did not run")
	}

	joined := ""
	for _, c := range calls {
		joined += strings.Join(c.args, " ") + "\n"
	}
	for _, want := range []string{"go mod tidy -diff", "go build ./...", "go tool buf lint", "go tool buf breaking --against .git#branch=dev"} {
		if !strings.Contains(joined, want) {
			t.Errorf("commands lack %q:\n%s", want, joined)
		}
	}
	if strings.Contains(joined, "govulncheck") {
		t.Error("a skipped check ran")
	}
}

func TestProtoOnlyWithAPI(t *testing.T) {
	checks := lint.Checks(lint.Options{Modules: []string{"postgres"}}, nil, nil)
	for _, c := range checks {
		if c.Name == "proto" {
			t.Fatal("proto checks without the api module")
		}
	}
	if checks[len(checks)-1].Name != "security" {
		t.Errorf("the vulnerability scan must run last: %v", checks[len(checks)-1].Name)
	}
}
