// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: platformtest/v1/echo.proto

// Test service of the api module: one call that validates and answers, one that fails on
// demand, so the tests cover the interceptors and the gateway end to end.

package platformtestv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageText   string                 `protobuf:"bytes,1,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_platformtest_v1_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_v1_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_platformtest_v1_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageText   string                 `protobuf:"bytes,1,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Shouted       bool                   `protobuf:"varint,3,opt,name=shouted,proto3" json:"shouted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_platformtest_v1_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_v1_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_platformtest_v1_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *EchoResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *EchoResponse) GetShouted() bool {
	if x != nil {
		return x.Shouted
	}
	return false
}

type FailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// panic, internal, not_found or slow
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_platformtest_v1_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_v1_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_platformtest_v1_echo_proto_rawDescGZIP(), []int{2}
}

func (x *FailRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type FailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_platformtest_v1_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_platformtest_v1_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_platformtest_v1_echo_proto_rawDescGZIP(), []int{3}
}

var File_platformtest_v1_echo_proto protoreflect.FileDescriptor

const file_platformtest_v1_echo_proto_rawDesc = "" +
	"\n" +
	"\x1aplatformtest/v1/echo.proto\x12\x0fplatformtest.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\";\n" +
	"\vEchoRequest\x12,\n" +
	"\fmessage_text\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x14R\vmessageText\"c\n" +
	"\fEchoResponse\x12!\n" +
	"\fmessage_text\x18\x01 \x01(\tR\vmessageText\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x18\n" +
	"\ashouted\x18\x03 \x01(\bR\ashouted\"!\n" +
	"\vFailRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\"\x0e\n" +
	"\fFailResponse2\xc5\x01\n" +
	"\vEchoService\x12X\n" +
	"\x04Echo\x12\x1c.platformtest.v1.EchoRequest\x1a\x1d.platformtest.v1.EchoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/echo\x12\\\n" +
	"\x04Fail\x12\x1c.platformtest.v1.FailRequest\x1a\x1d.platformtest.v1.FailResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/fail/{kind}B`Z^github.com/aidarbn/platform-go/kit/modules/api/internal/testapi/platformtest/v1;platformtestv1b\x06proto3"

var (
	file_platformtest_v1_echo_proto_rawDescOnce sync.Once
	file_platformtest_v1_echo_proto_rawDescData []byte
)

func file_platformtest_v1_echo_proto_rawDescGZIP() []byte {
	file_platformtest_v1_echo_proto_rawDescOnce.Do(func() {
		file_platformtest_v1_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platformtest_v1_echo_proto_rawDesc), len(file_platformtest_v1_echo_proto_rawDesc)))
	})
	return file_platformtest_v1_echo_proto_rawDescData
}

var file_platformtest_v1_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_platformtest_v1_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: platformtest.v1.EchoRequest
	(*EchoResponse)(nil), // 1: platformtest.v1.EchoResponse
	(*FailRequest)(nil),  // 2: platformtest.v1.FailRequest
	(*FailResponse)(nil), // 3: platformtest.v1.FailResponse
}
var file_platformtest_v1_echo_proto_depIdxs = []int32{
	0, // 0: platformtest.v1.EchoService.Echo:input_type -> platformtest.v1.EchoRequest
	2, // 1: platformtest.v1.EchoService.Fail:input_type -> platformtest.v1.FailRequest
	1, // 2: platformtest.v1.EchoService.Echo:output_type -> platformtest.v1.EchoResponse
	3, // 3: platformtest.v1.EchoService.Fail:output_type -> platformtest.v1.FailResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platformtest_v1_echo_proto_init() }
func file_platformtest_v1_echo_proto_init() {
	if File_platformtest_v1_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platformtest_v1_echo_proto_rawDesc), len(file_platformtest_v1_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_platformtest_v1_echo_proto_goTypes,
		DependencyIndexes: file_platformtest_v1_echo_proto_depIdxs,
		MessageInfos:      file_platformtest_v1_echo_proto_msgTypes,
	}.Build()
	File_platformtest_v1_echo_proto = out.File
	file_platformtest_v1_echo_proto_goTypes = nil
	file_platformtest_v1_echo_proto_depIdxs = nil
}
