package codemod_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/aidarbn/platform-go/internal/codemod"
)

const riverx = "github.com/aidarbn/platform-go/kit/modules/riverx"

func project(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestPending(t *testing.T) {
	all := []codemod.Codemod{
		{Version: "v0.4.0", Name: "c"},
		{Version: "v0.3.0", Name: "a"},
		{Version: "v0.3.1", Name: "b"},
	}
	names := func(mods []codemod.Codemod) string {
		var out []string
		for _, m := range mods {
			out = append(out, m.Name)
		}
		return strings.Join(out, ",")
	}
	for applied, want := range map[string]string{
		"":       "a,b,c",
		"v0.2.2": "a,b,c",
		"v0.3.0": "b,c",
		"v0.4.0": "",
		"dev":    "a,b,c",
	} {
		if got := names(codemod.Pending(all, applied)); got != want {
			t.Errorf("Pending(%q) = %q, want %q", applied, got, want)
		}
	}
}

func TestRenameSymbol(t *testing.T) {
	dir := project(t, map[string]string{
		"internal/jobs/jobs.go": `package jobs

import (
	"context"

	rx "` + riverx + `"
)

// Enqueue puts the job into the queue.
func Enqueue(ctx context.Context, q *rx.Queue) error {
	_, err := rx.Insert(ctx, q) // keep this comment
	return err
}

func shadowed() {
	rx := struct{ Insert int }{}
	_ = rx.Insert
}
`,
		"cmd/app/other.go": `package main

import "fmt"

func Insert() { fmt.Println("not riverx") }

func use() { fmt.Insert() }
`,
		"cmd/app/modules.gen.go": `// Code generated by platformgo from platformgo.yaml. DO NOT EDIT.

package main

import "` + riverx + `"

var _ = riverx.Insert
`,
		"vendor/x/x.go": "package x\n\nimport \"" + riverx + "\"\n\nvar _ = riverx.Insert\n",
	})
	mods := []codemod.Codemod{codemod.RenameSymbol("v0.3.0", riverx, "Insert", "Enqueue")}

	changes, err := codemod.Run(dir, mods)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if len(changes) != 1 || changes[0].Path != "internal/jobs/jobs.go" {
		t.Fatalf("changes = %+v", changes)
	}
	got := string(changes[0].Content)
	for _, want := range []string{"rx.Enqueue(ctx, q) // keep this comment", "// Enqueue puts the job into the queue.", "_ = rx.Insert"} {
		if !strings.Contains(got, want) {
			t.Errorf("result lacks %q:\n%s", want, got)
		}
	}
	if changes[0].Codemods[0] != "riverx.Insert→Enqueue" {
		t.Errorf("codemods = %v", changes[0].Codemods)
	}

	// Idempotent: the rewritten project has nothing left.
	os.WriteFile(filepath.Join(dir, changes[0].Path), changes[0].Content, 0o644)
	if again, err := codemod.Run(dir, mods); err != nil || len(again) != 0 {
		t.Errorf("second run: %+v, %v", again, err)
	}
}

func TestStepsChain(t *testing.T) {
	dir := project(t, map[string]string{
		"a.go": "package a\n\nimport \"" + riverx + "\"\n\nvar _ = riverx.Old\n",
	})
	mods := codemod.Pending([]codemod.Codemod{
		codemod.RenameSymbol("v0.4.0", riverx, "Middle", "New"),
		codemod.RenameSymbol("v0.3.0", riverx, "Old", "Middle"),
	}, "v0.2.0")
	changes, err := codemod.Run(dir, mods)
	if err != nil || len(changes) != 1 {
		t.Fatalf("%+v, %v", changes, err)
	}
	if !strings.Contains(string(changes[0].Content), "riverx.New") || len(changes[0].Codemods) != 2 {
		t.Errorf("steps did not chain:\n%s %v", changes[0].Content, changes[0].Codemods)
	}
}

func TestBrokenFilesAreLeftAlone(t *testing.T) {
	dir := project(t, map[string]string{"a.go": "package a\n\nfunc {"})
	mods := []codemod.Codemod{codemod.RenameSymbol("v0.3.0", riverx, "Old", "New")}
	if changes, err := codemod.Run(dir, mods); err != nil || len(changes) != 0 {
		t.Errorf("%+v, %v", changes, err)
	}
}

func TestAllAreOrderedAndNamed(t *testing.T) {
	seen := map[string]bool{}
	for _, m := range codemod.All() {
		if m.Name == "" || m.Fix == nil || seen[m.Name] {
			t.Errorf("codemod %+v is incomplete or repeated", m)
		}
		seen[m.Name] = true
	}
}
