// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: platform/i18n/v1/i18n.proto

// Translatable fields of API messages, ported from taply.

package i18npb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// I18nFieldOptions marks a string field as translatable.
//
// key is "<entity>.<field>": the entity type before the dot, the translated field after
// it. It is the entity and field columns of the i18n_translations table and the key of a
// field_translations map.
//
// instance_key is the name of the sibling field that holds the id of the entity, such as
// "id". Without it the translation is shared by every instance.
//
// For every response the i18n interceptor walks the message tree, reads the ids of the
// annotated fields, loads their translations in one query per entity type and replaces
// the values with the translation for the Accept-Language of the request. A message with
// a field_translations map is left alone: it belongs to an editor, which reads and writes
// every locale itself.
//
//	message Product {
//	  int64 id = 1;
//	  string name = 2 [(platform.i18n.v1.i18n_field) = {key: "product.name", instance_key: "id"}];
//	  map<string, platform.i18n.v1.LocaleMap> field_translations = 10;
//	}
type I18NFieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	InstanceKey   string                 `protobuf:"bytes,2,opt,name=instance_key,json=instanceKey,proto3" json:"instance_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I18NFieldOptions) Reset() {
	*x = I18NFieldOptions{}
	mi := &file_platform_i18n_v1_i18n_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I18NFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I18NFieldOptions) ProtoMessage() {}

func (x *I18NFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_platform_i18n_v1_i18n_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I18NFieldOptions.ProtoReflect.Descriptor instead.
func (*I18NFieldOptions) Descriptor() ([]byte, []int) {
	return file_platform_i18n_v1_i18n_proto_rawDescGZIP(), []int{0}
}

func (x *I18NFieldOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *I18NFieldOptions) GetInstanceKey() string {
	if x != nil {
		return x.InstanceKey
	}
	return ""
}

// LocaleMap holds the translations of one field: locale to text.
type LocaleMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocaleMap) Reset() {
	*x = LocaleMap{}
	mi := &file_platform_i18n_v1_i18n_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocaleMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocaleMap) ProtoMessage() {}

func (x *LocaleMap) ProtoReflect() protoreflect.Message {
	mi := &file_platform_i18n_v1_i18n_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocaleMap.ProtoReflect.Descriptor instead.
func (*LocaleMap) Descriptor() ([]byte, []int) {
	return file_platform_i18n_v1_i18n_proto_rawDescGZIP(), []int{1}
}

func (x *LocaleMap) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

var file_platform_i18n_v1_i18n_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*I18NFieldOptions)(nil),
		Field:         50001,
		Name:          "platform.i18n.v1.i18n_field",
		Tag:           "bytes,50001,opt,name=i18n_field",
		Filename:      "platform/i18n/v1/i18n.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional platform.i18n.v1.I18nFieldOptions i18n_field = 50001;
	E_I18NField = &file_platform_i18n_v1_i18n_proto_extTypes[0]
)

var File_platform_i18n_v1_i18n_proto protoreflect.FileDescriptor

const file_platform_i18n_v1_i18n_proto_rawDesc = "" +
	"\n" +
	"\x1bplatform/i18n/v1/i18n.proto\x12\x10platform.i18n.v1\x1a google/protobuf/descriptor.proto\"G\n" +
	"\x10I18nFieldOptions\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\finstance_key\x18\x02 \x01(\tR\vinstanceKey\"\x87\x01\n" +
	"\tLocaleMap\x12?\n" +
	"\x06values\x18\x01 \x03(\v2'.platform.i18n.v1.LocaleMap.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:b\n" +
	"\n" +
	"i18n_field\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\".platform.i18n.v1.I18nFieldOptionsR\ti18nFieldB8Z6github.com/aidarbn/platform-go/kit/i18nx/i18npb;i18npbb\x06proto3"

var (
	file_platform_i18n_v1_i18n_proto_rawDescOnce sync.Once
	file_platform_i18n_v1_i18n_proto_rawDescData []byte
)

func file_platform_i18n_v1_i18n_proto_rawDescGZIP() []byte {
	file_platform_i18n_v1_i18n_proto_rawDescOnce.Do(func() {
		file_platform_i18n_v1_i18n_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_i18n_v1_i18n_proto_rawDesc), len(file_platform_i18n_v1_i18n_proto_rawDesc)))
	})
	return file_platform_i18n_v1_i18n_proto_rawDescData
}

var file_platform_i18n_v1_i18n_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_platform_i18n_v1_i18n_proto_goTypes = []any{
	(*I18NFieldOptions)(nil),          // 0: platform.i18n.v1.I18nFieldOptions
	(*LocaleMap)(nil),                 // 1: platform.i18n.v1.LocaleMap
	nil,                               // 2: platform.i18n.v1.LocaleMap.ValuesEntry
	(*descriptorpb.FieldOptions)(nil), // 3: google.protobuf.FieldOptions
}
var file_platform_i18n_v1_i18n_proto_depIdxs = []int32{
	2, // 0: platform.i18n.v1.LocaleMap.values:type_name -> platform.i18n.v1.LocaleMap.ValuesEntry
	3, // 1: platform.i18n.v1.i18n_field:extendee -> google.protobuf.FieldOptions
	0, // 2: platform.i18n.v1.i18n_field:type_name -> platform.i18n.v1.I18nFieldOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_platform_i18n_v1_i18n_proto_init() }
func file_platform_i18n_v1_i18n_proto_init() {
	if File_platform_i18n_v1_i18n_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_i18n_v1_i18n_proto_rawDesc), len(file_platform_i18n_v1_i18n_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_platform_i18n_v1_i18n_proto_goTypes,
		DependencyIndexes: file_platform_i18n_v1_i18n_proto_depIdxs,
		MessageInfos:      file_platform_i18n_v1_i18n_proto_msgTypes,
		ExtensionInfos:    file_platform_i18n_v1_i18n_proto_extTypes,
	}.Build()
	File_platform_i18n_v1_i18n_proto = out.File
	file_platform_i18n_v1_i18n_proto_goTypes = nil
	file_platform_i18n_v1_i18n_proto_depIdxs = nil
}
